version: "3.8"
services:
db:
image: mysql:5.7
environment:
MYSQL_ROOT_PASSWORD: example
MYSQL_DATABASE: wordpress
MYSQL_USER: wp
MYSQL_PASSWORD: wp
volumes:
- db_data:/var/lib/mysql
healthcheck:
test: ["CMD","mysqladmin","ping","-h","localhost"]
interval: 5s
timeout: 5s
retries: 10


wordpress:
image: wordpress:5.8-php7.4-apache
depends_on:
db:
condition: service_healthy
ports:
- "8000:80"
environment:
WORDPRESS_DB_HOST: db:3306
WORDPRESS_DB_USER: wp
WORDPRESS_DB_PASSWORD: wp
WORDPRESS_DB_NAME: wordpress
volumes:
- ../wp-content:/var/www/html/wp-content
- ../flags:/var/www/html/flags
- ../init-scripts:/init-scripts
entrypoint: ["/bin/bash","/init-scripts/entrypoint.sh"]


volumes:
db_data:
